export type Expr = { type:'Literal'; value:number|string|boolean } | { type:'Variable'; name:string } | { type:'Binary'; operator:string; left:Expr; right:Expr } | { type:'Unary'; operator:string; operand:Expr };
export type Statement = { type:'Declaration'; name:string; kind:string; value:Expr } | { type:'Assignment'; name:string; value:Expr } | { type:'Print'; value:Expr } | { type:'If'; condition:Expr; then:Statement[]; otherwise:Statement[] } | { type:'While'; condition:Expr; body:Statement[] } | { type:'DoWhile'; condition:Expr; body:Statement[] } | { type:'For'; initial:Statement; condition:Expr; update:Statement; body:Statement[] };
export type Program = {type:'Program';body:Statement[]};
type Value=number|string|boolean;
export function tokenize(source:string):string[]{
 const tokens:string[]=[];let pos=0;
 const token=/"(?:\\["\\nrt]|[^"\\\n])*"|\d+(?:\.\d+)?|[A-Za-z_áéíóúñ][\wáéíóúñ]*|>=|<=|==|!=|\+\+|--|&&|\|\||[{}();=+*/%<>!.-]/y;
 while(pos<source.length){if(/\s/.test(source[pos])){pos++;continue}if(source.slice(pos,pos+2)==='//'){const end=source.indexOf('\n',pos);pos=end<0?source.length:end;continue}token.lastIndex=pos;const match=token.exec(source);if(!match)throw new Error(`Carácter no admitido en la posición ${pos+1}: «${source[pos]}».`);tokens.push(match[0]);pos=token.lastIndex}
 if(tokens.length>4000)throw new Error('El ejemplo es demasiado largo. Usa menos de 4000 tokens.');return tokens;
}
export function parse(tokens:string[]):Program {
 let i=0,depth=0;const peek=()=>tokens[i];const take=(expected:string)=>{if(tokens[i]!==expected)throw new Error(`Se esperaba «${expected}» y se encontró «${tokens[i]||'fin del código'}».`);i++};
 function identifier(){const name=tokens[i++];if(!/^[A-Za-z_]\w*$/.test(name||'')||['si','sino','mientras','para','escribir','int','double','string','bool','numero','texto','if','else','while','for','true','false'].includes(name))throw new Error('Se esperaba un nombre de variable válido.');return name}
 function atom():Expr {if(++depth>100)throw new Error('El ejemplo tiene demasiados niveles de anidación.');try{const t=tokens[i++];if(!t)throw new Error('La expresión está incompleta.');if(t==='('){const e=expression();take(')');return e}if(['-','!','+'].includes(t))return {type:'Unary',operator:t,operand:atom()};if(/^\d/.test(t))return {type:'Literal',value:Number(t)};if(t.startsWith('"'))return {type:'Literal',value:JSON.parse(t)};if(['true','false','verdadero','falso'].includes(t))return {type:'Literal',value:t==='true'||t==='verdadero'};if(/^[A-Za-z_]\w*$/.test(t))return {type:'Variable',name:t};throw new Error(`Expresión inválida: «${t}».`)}finally{depth--}}
 function binary(next:()=>Expr,ops:string[]):Expr{let e=next();while(ops.includes(peek())){const operator=tokens[i++];e={type:'Binary',operator,left:e,right:next()}}return e}
 const product=()=>binary(atom,['*','/','%']);const sum=()=>binary(product,['+','-']);const compare=()=>binary(sum,['>','<','>=','<=']);const equality=()=>binary(compare,['==','!=']);const and=()=>binary(equality,['&&']);const expression=()=>binary(and,['||']);
 function assignment():Statement{const name=identifier();if(['++','--'].includes(peek())){const op=tokens[i++];return {type:'Assignment',name,value:{type:'Binary',operator:op==='++'?'+':'-',left:{type:'Variable',name},right:{type:'Literal',value:1}}}}take('=');return {type:'Assignment',name,value:expression()}}
 function declaration():Statement{const kind=tokens[i++],name=identifier();take('=');return {type:'Declaration',name,kind,value:expression()}}
 function block():Statement[]{if(peek()!=='{')return [statement()];take('{');const body:Statement[]=[];while(peek()&&peek()!=='}')body.push(statement());take('}');return body}
 function statement():Statement {if(++depth>100)throw new Error('Hay demasiados bloques anidados.');try{
 const t=peek();if(['numero','texto','int','double','string','bool'].includes(t)){const s=declaration();take(';');return s}
 if(t==='escribir'||t==='Console'){i++;if(t==='Console'){take('.');take('WriteLine')}take('(');const value=expression();take(')');take(';');return {type:'Print',value}}
 if(t==='si'||t==='if'){i++;take('(');const condition=expression();take(')');const then=block();let otherwise:Statement[]=[];if(peek()==='sino'||peek()==='else'){i++;otherwise=block()}return {type:'If',condition,then,otherwise}}
 if(t==='mientras'||t==='while'){i++;take('(');const condition=expression();take(')');return {type:'While',condition,body:block()}}
 if(t==='do'){i++;const body=block();take('while');take('(');const condition=expression();take(')');take(';');return {type:'DoWhile',condition,body}}
 if(t==='para'||t==='for'){i++;take('(');const initial=['numero','int'].includes(peek())?declaration():assignment();take(';');const condition=expression();take(';');const update=assignment();take(')');return {type:'For',initial,condition,update,body:block()}}
 if(!t)throw new Error('El programa está incompleto.');const s=assignment();take(';');return s;
 }finally{depth--}}
 const body:Statement[]=[];while(i<tokens.length)body.push(statement());return {type:'Program',body};
}
function execute(ast:Program){
 const scopes:Map<string,{kind:string;value:Value}>[]=[new Map()];const output:string[]=[];let steps=0;
 const tick=()=>{if(++steps>10000)throw new Error('Se alcanzó el límite de 10 000 pasos. Revisa si el ciclo termina.');};
 const find=(name:string)=>{for(let n=scopes.length-1;n>=0;n--){const v=scopes[n].get(name);if(v)return v}throw new Error(`La variable «${name}» no está declarada.`)};
 const number=(v:Value)=>{if(typeof v!=='number')throw new Error('Esta operación requiere números.');return v};
 const boolean=(v:Value)=>{if(typeof v!=='boolean')throw new Error('La condición debe ser una comparación o un booleano.');return v};
 function evaluate(e:Expr):Value{tick();if(e.type==='Literal')return e.value;if(e.type==='Variable')return find(e.name).value;if(e.type==='Unary'){const v=evaluate(e.operand);return e.operator==='!'?!boolean(v):e.operator==='-'?-number(v):number(v)}
 const a=evaluate(e.left);if(e.operator==='&&')return boolean(a)&&boolean(evaluate(e.right));if(e.operator==='||')return boolean(a)||boolean(evaluate(e.right));const b=evaluate(e.right);
 switch(e.operator){case '+':return typeof a==='string'||typeof b==='string'?String(a)+String(b):number(a)+number(b);case '-':return number(a)-number(b);case '*':return number(a)*number(b);case '/':case '%':{const x=number(a),y=number(b);if(y===0)throw new Error('No se puede dividir entre cero.');return e.operator==='/'?x/y:x%y}case '>':return number(a)>number(b);case '<':return number(a)<number(b);case '>=':return number(a)>=number(b);case '<=':return number(a)<=number(b);case '==':return a===b;case '!=':return a!==b;default:throw new Error('Operador no admitido.')}
 }
 function validate(kind:string,v:Value){if(['int','double','numero'].includes(kind)){number(v);if(kind==='int'&&!Number.isInteger(v))throw new Error('int requiere un número entero.')}if(['string','texto'].includes(kind)&&typeof v!=='string')throw new Error('La variable requiere un texto.');if(kind==='bool')boolean(v)}
 function block(body:Statement[]){scopes.push(new Map());try{body.forEach(statement)}finally{scopes.pop()}}
 function statement(s:Statement){tick();switch(s.type){case 'Declaration':{const current=scopes[scopes.length-1];if(current.has(s.name))throw new Error(`«${s.name}» ya está declarada en este bloque.`);const value=evaluate(s.value);validate(s.kind,value);current.set(s.name,{kind:s.kind,value});break}case 'Assignment':{const variable=find(s.name),value=evaluate(s.value);validate(variable.kind,value);variable.value=value;break}case 'Print':output.push(String(evaluate(s.value)));if(output.join('').length>30000)throw new Error('La salida excede el límite del laboratorio.');break;case 'If':block(boolean(evaluate(s.condition))?s.then:s.otherwise);break;case 'DoWhile':do{tick();block(s.body)}while(boolean(evaluate(s.condition)));break;case 'While':while(boolean(evaluate(s.condition))){tick();block(s.body)}break;case 'For':scopes.push(new Map());try{statement(s.initial);while(boolean(evaluate(s.condition))){tick();block(s.body);statement(s.update)}}finally{scopes.pop()}break}}
 ast.body.forEach(statement);return {output:output.join('\n')||'(Sin salida)',steps};
}
function expressionText(e:Expr):string{if(e.type==='Literal')return typeof e.value==='string'?JSON.stringify(e.value):String(e.value);if(e.type==='Variable')return e.name;if(e.type==='Unary')return `${e.operator}${expressionText(e.operand)}`;return `(${expressionText(e.left)} ${e.operator} ${expressionText(e.right)})`}
function generate(body:Statement[],level=0):string{const indent='  '.repeat(level);return body.map(s=>{const line=(v:string)=>indent+v;const block=(b:Statement[])=>`{\n${generate(b,level+1)}\n${indent}}`;switch(s.type){case 'Declaration':return line(`${s.kind==='numero'?'double':s.kind==='texto'?'string':s.kind} ${s.name} = ${expressionText(s.value)};`);case 'Assignment':return line(`${s.name} = ${expressionText(s.value)};`);case 'Print':return line(`Console.WriteLine(${expressionText(s.value)});`);case 'If':return line(`if (${expressionText(s.condition)}) ${block(s.then)}${s.otherwise.length?' else '+block(s.otherwise):''}`);case 'DoWhile':return line(`do ${block(s.body)} while (${expressionText(s.condition)});`);case 'While':return line(`while (${expressionText(s.condition)}) ${block(s.body)}`);case 'For':return line(`for (${generate([s.initial]).trim().replace(/;$/,'')}; ${expressionText(s.condition)}; ${generate([s.update]).trim().replace(/;$/,'')}) ${block(s.body)}`)}}).join('\n')}
export function compile(source:string){const tokens=tokenize(source),ast=parse(tokens),result=execute(ast);return {tokens,ast,...result,generated:generate(ast.body)}}
