'use client';
import { useEffect, useRef, useState } from 'react';
import { Artwork, Flower } from './artwork';
import Link from 'next/link';
import { modules, slugs } from './modules';
import { CursorTrail, Reveal } from './motion';
import GuidedLab from './guided-lab';
import CourseSearch from './course-search';
import type {SearchHit} from './learning-search';
import { ArrowUpRight, ArrowRight, Play, ChevronLeft, ChevronRight, Braces, GitBranch, Terminal, Check, X, Menu, BookOpen, RotateCcw, Code2, Layers, MousePointer2 } from 'lucide-react';

export default function Home(){
 const [selected,setSelected]=useState(0),[completed,setCompleted]=useState<number[]>([]),[menu,setMenu]=useState(false),[search,setSearch]=useState(''),[searchHits,setSearchHits]=useState<SearchHit[]>([]);const track=useRef<HTMLDivElement>(null);const hero=useRef<HTMLDivElement>(null);
 useEffect(()=>{try{setCompleted(JSON.parse(localStorage.getItem('nexo-project-progress-v2')||'[]'))}catch{}},[]);
 useEffect(()=>{const shortcut=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){const field=document.querySelector<HTMLInputElement>('.nav-search input');if(field&&field.offsetWidth){e.preventDefault();field.focus()}}};document.addEventListener('keydown',shortcut);return()=>document.removeEventListener('keydown',shortcut)},[]);
 function choose(n:number){setSelected(n)}
 return <main><Reveal/>
 <header className="nav"><a className="brand" href="#"><span className="brand-icon"><Braces size={26}/></span><span>nexo<span className="brand-dot">.</span><small>APRENDE. CREA. CONECTA.</small></span></a><CourseSearch onResults={(query,hits)=>{setSearch(query);setSearchHits(hits);if(track.current)track.current.scrollLeft=0}}/><nav className={menu?'nav-links open':'nav-links'}><a href="#modulos" onClick={()=>setMenu(false)}>Aprender</a><Link href="/compilador" onClick={()=>setMenu(false)}>C# online</Link><a href="#laboratorio" onClick={()=>setMenu(false)}>Laboratorio <span className="tiny-dot"/></a><a href="#metodo" onClick={()=>setMenu(false)}>El método</a></nav><a className="nav-cta" href="#modulos">Comenzar gratis <ArrowUpRight size={16}/></a><button className="mobile-menu" aria-label="Abrir navegación" onClick={()=>setMenu(!menu)}><Menu/></button></header>
 <section className="hero section-wrap" ref={hero} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();hero.current?.style.setProperty('--mx',`${(e.clientX-r.left-r.width/2)/40}px`);hero.current?.style.setProperty('--my',`${(e.clientY-r.top-r.height/2)/35}px`)}} onMouseLeave={()=>{hero.current?.style.setProperty('--mx','0px');hero.current?.style.setProperty('--my','0px')}}>
 <div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> APRENDE COMPILADORES. CONSTRUYE POSIBILIDADES.</div><h1>Detrás de cada programa,<br/>hay un mundo.<br/><span>Descubre cómo funciona.</span></h1><p>De tu primera línea a tu propio compilador.<br/>Aprende con ejemplos, experimenta en tiempo real<br/>y conecta la teoría con lo que puedes crear.</p><div className="hero-actions"><a href="#modulos" className="button primary">Comenzar a aprender <ArrowRight size={18}/></a><a href="#laboratorio" className="button secondary"><Play size={15}/> Probar el laboratorio</a></div><div className="hero-meta"><span><Check size={14}/> Gratis y a tu ritmo</span><span><Check size={14}/> Sin instalaciones</span></div></div>
 <div className="hero-float-cards">{[0,2,3,5].map((n,i)=><Link key={n} className={`hero-course hero-course-${i}`} href={`/aprender/${slugs[n]}`}><Artwork kind={n}/><div><small>APRENDE HACIENDO</small><strong>{modules[n].name}</strong><span>{modules[n].topic} <ArrowUpRight size={14}/></span></div></Link>)}</div><div className="hero-mouse"><MousePointer2 size={14}/> Mueve el mouse. Todo está conectado.</div>
 <div className="hero-foot"><span>UN ESPACIO PARA APRENDER CREANDO</span><span><b>Aprende a programar.</b> Crea algo tuyo.</span><a href="#modulos">DESCUBRE TU RUTA ↓</a></div></section>
 <section className="learning-strip section-wrap"><div><span className="strip-symbol">✳</span><h2>Una pequeña idea.<br/><span>Una nueva habilidad.</span></h2></div><a href="#laboratorio"><span className="strip-number">01</span><strong>Escribe algo</strong><p>Una línea es suficiente para empezar.</p><ArrowUpRight/></a><a href="#laboratorio"><span className="strip-number">02</span><strong>Mira qué sucede</strong><p>Explora el viaje de tu código.</p><ArrowUpRight/></a><a href="#modulos"><span className="strip-number">03</span><strong>Hazlo tuyo</strong><p>Experimenta. Equivócate. Vuelve a probar.</p><ArrowUpRight/></a></section>
 <section id="modulos" className="modules-section section-wrap"><div className="section-heading"><div><div className="eyebrow muted">01 / TU RUTA DE APRENDIZAJE</div><h2>Elige qué aprender hoy <Flower className="heading-flower"/></h2></div><div className="heading-aside"><p>Doce compiladores. De tu primera línea<br/>a entender el programa completo.</p><div className="carousel-controls"><span>{String(completed.length).padStart(2,'0')} / 12 completados</span><button aria-label="Módulos anteriores" onClick={()=>track.current?.scrollBy({left:-350,behavior:'smooth'})}><ChevronLeft size={18}/></button><button aria-label="Más módulos" onClick={()=>track.current?.scrollBy({left:350,behavior:'smooth'})}><ChevronRight size={18}/></button></div></div></div><div className="module-track" ref={track}>{(search.trim()?searchHits.map(hit=>({m:modules[hit.index],n:hit.index})):modules.map((m,n)=>({m,n}))).map(({m,n})=><Link key={m.name} className={`module-card ${m.color}`} href={`/aprender/${slugs[n]}`}><div className="card-top"><span>MÓDULO {String(n+1).padStart(2,'0')}</span>{completed.includes(n)?<Check size={17}/>:<ArrowUpRight size={17}/>}</div><div className="module-art"><Artwork kind={n}/><span className="art-course-label">{m.name}</span></div><div className="card-content"><small>{m.level} · {m.target}</small><h3>{m.name}</h3><p>{m.desc}</p><div className="card-footer"><span>{m.artifact}</span><span>{n<5?'12':n===11?'35':'22'} MIN <ArrowRight size={14}/></span></div></div></Link>)}</div>{search.trim()&&!searchHits.length&&<p className="empty-search">No encontramos ese tema. Prueba con “crear ventanas”, “repetir instrucciones” o “variables”.</p>}</section>
 <section id="laboratorio" className="lab-section section-wrap"><div className="section-heading"><div><div className="eyebrow muted">02 / MENOS TEORÍA SUELTA. MÁS CONEXIONES.</div><h2>Aprendes cuando<br/><span className="cyan-text">lo haces funcionar.</span></h2></div><div className="lab-intro">Cambia una línea. Ejecuta el código.<br/>Mira qué sucede en cada etapa.<br/><b>Este laboratorio es tuyo.</b><Link className="real-editor-link" href="/compilador">Compilar C# <ArrowUpRight size={16}/></Link></div></div><div className="practice-composition"><div className="practice-notes"><div className="note-blue">Simple <span>✦</span></div><div className="note-green">A tu ritmo <span>{'{ }'}</span></div><div className="note-yellow"><strong>La mejor forma<br/>de entenderlo:<br/>hacerlo.</strong><Flower/><small>INTERACTIVO</small></div></div><GuidedLab exampleIndex={selected}/></div></section>
 <section id="metodo" className="method section-wrap"><div className="method-title"><div className="eyebrow muted">03 / CONSTRUIR PARA ENTENDER</div><h2>No memorices<br/>el camino.<br/><span>Recórrelo.</span></h2><p>La teoría cobra sentido cuando<br/>puedes experimentar con ella.</p></div><div className="method-steps">{[{icon:BookOpen,title:'Entiende una idea',text:'Lecciones breves, ejemplos claros y una ruta que avanza contigo.'},{icon:Code2,title:'Ponla a prueba',text:'Edita el código y observa cómo se transforma en cada etapa.'},{icon:GitBranch,title:'Conecta lo aprendido',text:'Comprueba tu conocimiento y continúa con el siguiente módulo.'}].map((s,n)=><div className="method-step" key={s.title}><span className="step-number">0{n+1}</span><s.icon size={24}/><div><h3>{s.title}</h3><p>{s.text}</p></div><ArrowUpRight size={20}/></div>)}</div></section>
 <section className="goals section-wrap"><div className="goal-chips">{['Entender los tokens','Escribir mi primer programa','Conectar la teoría','Explorar C#','Crear un compilador','Pensar en código'].map((t,n)=><a className={`goal-chip goal-${n}`} href={n===3?'#laboratorio':'#modulos'} key={t}>{t}</a>)}</div><div className="goals-copy"><span className="eyebrow">CADA GRAN PROYECTO EMPIEZA CON CURIOSIDAD</span><h2>Lo que hoy parece complejo,<br/>mañana puede ser <span>tu creación.</span></h2></div></section>
 <section className="project-section section-wrap"><div className="project-heading"><Flower/><h2>Te guardamos un lugar.<br/><span>Empieza por donde quieras.</span></h2></div><div className="project-cards">{[{kind:0,title:'Tu primera línea',text:'Descubre qué pasa cuando escribes Hola, mundo.',module:0,tag:'PARA EMPEZAR'},{kind:3,title:'Código que decide',text:'Experimenta con condiciones y construye dos caminos.',module:5,tag:'PARA EXPLORAR'},{kind:5,title:'De una idea a C#',text:'Sigue cada transformación hasta el lenguaje destino.',module:7,tag:'PARA CONECTAR'}].map(p=><button className={`project-card project-${p.kind}`} key={p.title} onClick={()=>{choose(p.module);document.getElementById('laboratorio')?.scrollIntoView({behavior:'smooth'})}}><Artwork kind={p.kind}/><small>{p.tag}</small><h3>{p.title}</h3><p>{p.text}</p><span>Entrar al laboratorio <ArrowUpRight size={20}/></span></button>)}</div></section>
 <section className="closing section-wrap magnetic-section"><CursorTrail/><span className="eyebrow">MENOS “ALGÚN DÍA”. MÁS “HOLA, MUNDO”.</span><h2>Tu próxima idea<br/>empieza <span>aquí.</span></h2><a className="button primary" href="#modulos">Comienza a hacerla realidad <ArrowRight size={18}/></a></section><footer className="footer section-wrap"><a className="brand" href="#">nexo<span className="brand-dot">.</span></a><span>Un espacio para aprender programación</span><a href="#laboratorio">Hecho para experimentar <ArrowUpRight size={14}/></a></footer>

 </main>
}

